baseURL: "https://tomhilder.github.io/"
title: Tom Hilder
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Research
          url: research/
          weight: 1
        - name: Software
          url: software/
          weight: 2
        - name: Talks
          url: talks/
          weight: 3
        - name: Blog
          url: blog/
          weight: 4

params:
    description: "Personal website of Tom Hilder, PhD Candidate at Monash University researching the ionised interstellar medium using computational statistics and scalable Gaussian Process methods."
    author: Tom Hilder
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["research","software","talks","blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tom Hilder
          subtitle: "PhD Candidate at the School of Physics & Astronomy, Monash University. I study the ionised interstellar medium using computational statistics, particularly cutting-edge scalable Gaussian Process methods."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Research
              url: research/
            - name: Software
              url: software/
            - name: Talks
              url: talks/
            - name: Blog
              url: blog/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: Email
          url: mailto:thomas.hilder@monash.edu
        - name: GitHub
          url: https://github.com/tomhilder
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=q0Ol5jsAAAAJ&hl=en
        - name: ORCID
          url: https://orcid.org/0000-0001-7641-5235
        - name: Bluesky
          url: https://bsky.app/profile/tom-hilder.bsky.social
        - name: YouTube
          url: "#"

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Tom Hilder"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2